/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controler.CN_User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import services.FillComboBox;
import services.INF;
import services.Table;

/**
 *
 * @author dirac
 */
public class AddUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddUser
     */
    public AddUser() throws Exception {
        initComponents();
        FillComboBox cb = new FillComboBox();
        String where = "employee.employee_id not in (select employee_id from a_user )";
        cb.fillCBWhere(jCB_employee, "name", Table.EMPLOYEE,where);
        cb.fillCB(jCB_Permission, "name", Table.PERMISSION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCB_employee = new javax.swing.JComboBox<>();
        tx_username = new javax.swing.JTextField();
        ps_PasswordFirst = new javax.swing.JPasswordField();
        ps_PasswordSec = new javax.swing.JPasswordField();
        bt_save = new javax.swing.JButton();
        jCB_Permission = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("إنشاء مستخدم");
        setName("JI_AddUser"); // NOI18N

        jLabel1.setText("اسم المستخدم");

        jLabel2.setText("كلمة المرور");

        jLabel3.setText("الموظف");

        jLabel4.setText("تأكيد كلمة المرور");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("إنشاء مستخدم");

        tx_username.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ps_PasswordFirst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ps_PasswordSec.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        bt_save.setText("تسجيل");
        bt_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_saveMouseClicked(evt);
            }
        });

        jLabel6.setText("الصلاحية");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCB_employee, 0, 188, Short.MAX_VALUE)
                        .addComponent(tx_username))
                    .addComponent(ps_PasswordFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCB_Permission, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ps_PasswordSec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCB_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tx_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ps_PasswordFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ps_PasswordSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_Permission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addComponent(bt_save, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_saveMouseClicked
        if (tx_username.getText().toString().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,"يجب وضع اسم للمستخدم");
            return;
        }
            
        if (ps_PasswordFirst.getText().toString().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null,"يجب وضع باسورد");
            return;
        }
        
        if(!ps_PasswordFirst.getText().toString().equals(ps_PasswordSec.getText().toString())){
            JOptionPane.showMessageDialog(null,"تأكد من كلمة المرور");
            return;
        }
        if (jCB_employee.getSelectedItem()== null){
            JOptionPane.showMessageDialog(null,"كل الموظفين مسجل لهم مستخدم");
            return;
        }
        int employee_ID = 0;
        int permission_ID = 0;
        String username = tx_username.getText().toString();
        String password = ps_PasswordFirst.getText().toString();
        try {
            employee_ID = INF.getIDFor(Table.EMPLOYEE, jCB_employee.getSelectedItem().toString());
            permission_ID = INF.getIDFor(Table.PERMISSION, jCB_Permission.getSelectedItem().toString());
            CN_User user = new CN_User();
            user.save(username, password, employee_ID, permission_ID);
            JOptionPane.showMessageDialog(null, "تم تسجيل اليوزر بنجاح");
        } catch (Exception ex) {
            Logger.getLogger(AddUser.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_bt_saveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_save;
    private javax.swing.JComboBox<String> jCB_Permission;
    private javax.swing.JComboBox<String> jCB_employee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField ps_PasswordFirst;
    private javax.swing.JPasswordField ps_PasswordSec;
    private javax.swing.JTextField tx_username;
    // End of variables declaration//GEN-END:variables
}
