/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controler.CN_Customer;
import Controler.CN_Login;
import Controler.CN_Orders;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import services.FillComboBox;
import services.INF;
import services.Table;
import static sun.misc.MessageUtils.where;

/**
 *
 * @author dirac
 */
public class OrderReview extends javax.swing.JFrame {

    /**
     * Creates new form OrderReview
     */
    public OrderReview() {
        initComponents();
        lb_reason.setVisible(false);
        tx_reason.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tx_reason = new javax.swing.JTextField();
        lb_reason = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tx_orderNo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tx_name = new javax.swing.JTextField();
        tx_Address = new javax.swing.JTextField();
        tx_Phone = new javax.swing.JTextField();
        tx_user = new javax.swing.JTextField();
        jc_driver = new javax.swing.JComboBox<>();
        jc_edit = new javax.swing.JCheckBox();
        dtpicker = new com.github.lgooddatepicker.components.DateTimePicker();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tx_description = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tx_grandtotal = new javax.swing.JTextField();
        tx_service = new javax.swing.JTextField();
        tx_AmtPurchase = new javax.swing.JTextField();
        jc_ordercomplete = new javax.swing.JCheckBox();
        jc_orderdelete = new javax.swing.JCheckBox();

        setTitle("مراجعة أوردر");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/Save-icon.png"))); // NOI18N
        jButton1.setText("تعديل");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/erase-128.png"))); // NOI18N
        jButton2.setText("إلغاء");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        tx_reason.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lb_reason.setText("الأسباب");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tx_reason, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_reason, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tx_reason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_reason)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("مراجعة أوردر");
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tx_orderNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx_orderNo.setText("مراجعة أوردر");
        tx_orderNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tx_orderNo.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 837, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tx_orderNo, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tx_orderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("إسم العميل");
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("إسم الكابتن");
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("القائم بأعمال الشحن");
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("هاتف العميل");
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("عنوان العميل");
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("التاريخ");
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tx_name.setEditable(false);
        tx_name.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tx_Address.setEditable(false);
        tx_Address.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tx_Phone.setEditable(false);
        tx_Phone.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tx_user.setEditable(false);
        tx_user.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tx_user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jc_driver.setEnabled(false);

        jc_edit.setText("تعديل البيانات");
        jc_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jc_editMouseClicked(evt);
            }
        });

        dtpicker.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(tx_Address)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(tx_Phone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jc_driver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(tx_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dtpicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(tx_user, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jc_edit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jc_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtpicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tx_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setName("JI_CreateOrder"); // NOI18N

        tx_description.setColumns(20);
        tx_description.setEditable(false);
        tx_description.setRows(5);
        tx_description.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(tx_description);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("ملاحظات :");
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("إجمالي المشتريات");
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("خدمة التوصيل");
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("الإجمالي");
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tx_grandtotal.setEditable(false);
        tx_grandtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_grandtotal.setText("0");
        tx_grandtotal.setBackground(new java.awt.Color(0, 0, 0));
        tx_grandtotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tx_grandtotal.setForeground(new java.awt.Color(0, 255, 0));
        tx_grandtotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx_grandtotalMouseClicked(evt);
            }
        });

        tx_service.setEditable(false);
        tx_service.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_service.setText("0");
        tx_service.setBackground(new java.awt.Color(0, 0, 0));
        tx_service.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tx_service.setForeground(new java.awt.Color(0, 255, 0));

        tx_AmtPurchase.setEditable(false);
        tx_AmtPurchase.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tx_AmtPurchase.setText("0");
        tx_AmtPurchase.setBackground(new java.awt.Color(0, 0, 0));
        tx_AmtPurchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tx_AmtPurchase.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(tx_grandtotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tx_service)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tx_AmtPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(79, 79, 79))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tx_grandtotal)
                    .addComponent(tx_service, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(tx_AmtPurchase, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jc_ordercomplete.setText("تم توصيل الأوردر بنجاح");
        jc_ordercomplete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jc_ordercompleteMouseClicked(evt);
            }
        });

        jc_orderdelete.setText("تم إلغاء الأوردر");
        jc_orderdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jc_orderdeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jc_orderdelete)
                        .addGap(25, 25, 25)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jc_ordercomplete)
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_ordercomplete)
                    .addComponent(jc_orderdelete)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Enter a password:");
        JPasswordField passw = new JPasswordField(10);
        panel.add(label);
        panel.add(passw);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Permission",
                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[1]);
        String pass ="";
        if (option == 0) // pressing OK button
        {
            char[] password = passw.getPassword();
             pass = new String(password);
            //System.out.println("Your password is: " + new String(password));
        }
       // String pass = JOptionPane.showInputDialog("هذه العملية تتطلب لباسورد الصلاحية  , من فضلك أدخل الباسورد");
        if (pass.equals("admin123")) {
            try {
                setUpdate();
            } catch (Exception ex) {
                Logger.getLogger(OrderReview.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Wrong password");
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jc_ordercompleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jc_ordercompleteMouseClicked
        if (jc_ordercomplete.isSelected()) {
            jc_orderdelete.setSelected(false);
            lb_reason.setVisible(false);
            tx_reason.setVisible(false);
        }
    }//GEN-LAST:event_jc_ordercompleteMouseClicked

    private void jc_orderdeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jc_orderdeleteMouseClicked
        if (jc_orderdelete.isSelected()) {
            jc_ordercomplete.setSelected(false);
            lb_reason.setVisible(true);
            tx_reason.setVisible(true);
        } else {
            lb_reason.setVisible(false);
            tx_reason.setVisible(false);
        }
    }//GEN-LAST:event_jc_orderdeleteMouseClicked

    private void jc_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jc_editMouseClicked
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Enter a password:");
        JPasswordField passw = new JPasswordField(10);
        panel.add(label);
        panel.add(passw);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "The title",
                JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options, options[1]);
        String pass ="";
        if (option == 0) // pressing OK button
        {
            char[] password = passw.getPassword();
             pass = new String(password);
            //System.out.println("Your password is: " + pass);
        }
        try {
            //String pass = JOptionPane.showInputDialog("هذه العملية تتطلب لباسورد الصلاحية  , من فضلك أدخل الباسورد");
            if (pass.equals("admin123")) {
                tx_AmtPurchase.setEditable(true);
                tx_service.setEditable(true);
                tx_description.setEditable(true);
                dtpicker.setEnabled(true);
                jc_driver.setEnabled(true);
                FillComboBox fill = new FillComboBox();
                String where = "status = 'FR' ";
                try {
                    fill.fillCBWhere(jc_driver, "name", Table.EMPLOYEE, where);
                } catch (Exception ex) {
                    Logger.getLogger(OrderReview.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                jc_edit.setSelected(false);
                JOptionPane.showMessageDialog(rootPane, "Wrong password");
            }
        } catch (Exception e) {
            jc_edit.setSelected(false);
        }

    }//GEN-LAST:event_jc_editMouseClicked

    private void tx_grandtotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx_grandtotalMouseClicked
        int AMT = Integer.parseInt(tx_AmtPurchase.getText().toString());
        int service = Integer.parseInt(tx_service.getText().toString());
        tx_grandtotal.setText("" + (AMT + service));
    }//GEN-LAST:event_tx_grandtotalMouseClicked

    public void setOrderNo(String no) throws Exception {
        tx_orderNo.setText(no);
        CN_Orders order = new CN_Orders();
        Hashtable<String, Map> data = order.getOrder(no);
        Map master = new HashMap();
        master = data.get("master");
        Map<String, String> lines = new HashMap();
        lines = data.get("lines");
        String name = master.get("customer").toString();
        String phone = master.get("phone").toString();
        String address = master.get("address").toString();
        String username = master.get("username").toString();
        String driver = master.get("driver").toString();
        String amtpurchase = master.get("amtpurchase").toString();
        String amtservice = master.get("amtservice").toString();
        String grandtotal = master.get("grandtotal").toString();
        String dateo = master.get("dateo").toString();
        String timeo = master.get("timeo").toString();
        String docstatus = master.get("docstatus").toString();
        tx_name.setText(name);
        tx_Address.setText(address);
        tx_Phone.setText(phone);
        tx_user.setText(username);
        jc_driver.addItem(driver);
        tx_AmtPurchase.setText(amtpurchase);
        tx_service.setText(amtservice);
        tx_grandtotal.setText(grandtotal);
        dtpicker.getDatePicker().setDate(LocalDate.parse(dateo));
        dtpicker.getTimePicker().setTime(LocalTime.parse(timeo));
        if (docstatus.equals("CO")) {
            jc_ordercomplete.setSelected(true);
        } else if (docstatus.equals("DL")) {
            jc_orderdelete.setSelected(true);
            lb_reason.setVisible(true);
            tx_reason.setVisible(true);
        } else {
            jc_ordercomplete.setSelected(false);
        }

        for (Map.Entry<String, String> entry : lines.entrySet()) {
            System.out.println(entry.getKey() + "/" + entry.getValue());
            tx_description.setText(tx_description.getText() + "" + entry.getValue() + "\n");
        }
    }

    public void setUpdate() throws Exception {
        CN_Customer co = new CN_Customer();
        CN_Orders or = new CN_Orders();
        Hashtable<String, Map> data = new Hashtable<>();
        Map master = new HashMap();
        Map lines = new HashMap();
        String dateTime = "";
        int driver_ID = 0;
        int lineNo = 1;
        String docstatus = "";
        if (jc_ordercomplete.isSelected()) {
            docstatus = "CO";
        } else if (jc_orderdelete.isSelected()) {
            docstatus = "DL";
        } else {
            docstatus = "PR";
        }
        try {
            String date = dtpicker.getTimePicker().getTime().toString();
            String time = dtpicker.getDatePicker().getDate().toString();
            dateTime = date + " " + time;
            driver_ID = INF.getIDFor(Table.EMPLOYEE, jc_driver.getSelectedItem().toString());
        } catch (Exception ex) {
            Logger.getLogger(CreateOrder.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "يجب وضع قيم للتاريخ و الوقت");
            return;
        }
        master.put("C_Order_ID", tx_orderNo.getText());
        master.put("Customer_ID", co.getCustomerID(tx_Phone.getText().toString()));
        master.put("dateordered", dateTime);
        master.put("docstatus", docstatus);
        master.put("driver_ID", driver_ID);
        master.put("amtpurchase", tx_AmtPurchase.getText().toString());
        master.put("amtservice", tx_service.getText().toString());
        master.put("grandtotal", tx_grandtotal.getText().toString());

        for (String line : tx_description.getText().split("\\n")) {
            lines.put(lineNo, line);
            lineNo = lineNo + 1;
        };
        data.put("master", master);
        data.put("lines", lines);
        or.update(data);
        JOptionPane.showMessageDialog(null, "Order Updated");
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderReview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DateTimePicker dtpicker;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jc_driver;
    private javax.swing.JCheckBox jc_edit;
    private javax.swing.JCheckBox jc_ordercomplete;
    private javax.swing.JCheckBox jc_orderdelete;
    private javax.swing.JLabel lb_reason;
    private javax.swing.JTextField tx_Address;
    private javax.swing.JTextField tx_AmtPurchase;
    private javax.swing.JTextField tx_Phone;
    private javax.swing.JTextArea tx_description;
    private javax.swing.JTextField tx_grandtotal;
    private javax.swing.JTextField tx_name;
    private javax.swing.JLabel tx_orderNo;
    private javax.swing.JTextField tx_reason;
    private javax.swing.JTextField tx_service;
    private javax.swing.JTextField tx_user;
    // End of variables declaration//GEN-END:variables
}
